// Single source of truth for the FAQ: feeds both the rendered /faq page and
// the FAQPage JSON-LD. Answers are HTML strings so they can carry links.

export type FaqItem = { q: string; a: string };
export type FaqSection = { heading: string; items: FaqItem[] };

export const faqSections: FaqSection[] = [
  {
    heading: "About Workings",
    items: [
      {
        q: "What is Workings?",
        a: "Workings is a software tool you install on your Mac or PC which allows you to collect and store a high-fidelity, tamper-evident record of your workflows locally. This record can be used to prove when and how your work was made, via verifiable reports and timelapses generated by Workings.",
      },
      {
        q: "What makes Workings different from other tools on the market?",
        a: "<p>Workings is not an AI detection tool. AI detectors look at the finished output and guess whether a human or a machine wrote it. They are statistically unreliable and disproportionately flag non-native speakers and certain writing styles.</p><p class=\"mt-3\">The only way to avoid guessing is to collect evidence of workflows at the point of creation.</p><p class=\"mt-3\">Workings collects high-fidelity, searchable data as you work — including screenshots, across every app — safe, private, local, and tamper-evident. You control who sees it, and anyone you share with can verify it for themselves. Every one of these features is vital, and Workings is the only point-of-creation tool that provides them all.</p>",
      },
      {
        q: "Who is Workings for?",
        a: "Workings is for where authorship matters — students can demonstrate the thinking and effort behind their work, inventors can show when and how their inventions were made, writers can share how they developed their creations. The core technology, allowing users to collect a database of high-fidelity evidence of workflows, can be developed into a wide array of functions for businesses.",
      },
      {
        q: "Who created Workings?",
        a: "Founded by seasoned product leaders from fintech, cyber, cryptography, consulting and games. Workings combines expertise in privacy, product design, crypto and AI, with patent-filed technology advancing the protection of authorship.",
      },
    ],
  },
  {
    heading: "Privacy & data",
    items: [
      {
        q: "Does Workings see my work?",
        a: "No. Workings is built on zero-knowledge architecture. All recording and processing happens on your device. The content of your work only ever leaves your machine if you send it. We literally cannot read it.",
      },
      {
        q: "What gets recorded?",
        a: 'Two things, both stored locally on your device: periodic screenshots of your screen, and your typing rhythm — the timing of how you work, not a log of your keystrokes. See the <a href="/privacy">Privacy Policy</a> for more details.',
      },
      {
        q: "Can I delete my data?",
        a: 'Yes. Everything lives on your device, you can delete your record any time. We hold no central database of your sessions. See the <a href="/privacy">Privacy Policy</a> for more detail.',
      },
    ],
  },
  {
    heading: "Reports & verification",
    items: [
      {
        q: "What's in a Workings report?",
        a: "A cryptographically signed summary of your session: duration, tool usage, AI use, behavioural metrics, a timeline visualisation, and a hash for verification. The amount of detail is your choice — you control what level of summary you share.",
      },
      {
        q: "When a Workings user provides me with their work and a Workings report, how do I know that I can trust them?",
        a: 'Drop their Workings report into our <a href="/verify">verifier</a> (no account needed). It confirms the report is genuine and unaltered, and that it\'s genuinely tied to the document they gave you — so now you\'re checking real, tamper-evident evidence, not taking their word for it. What that evidence tells you about their work is then yours to judge.',
      },
      {
        q: "What does the AI / human monitoring in a report mean?",
        a: "Workings monitors your session continuously and records which applications were active, including all known AI tools — how long you spent in each, and the order you moved between them (research, AI, editing, and so on). The report attests when it was monitoring and any gaps and shows this activity transparently. It doesn't read your content or measure how much of your work came from any tool — it shows how you worked, and proves it covered the whole process.",
      },
      {
        q: "Will my recordings become more useful over time?",
        a: "Yes. As you work, Workings lays down a genuine record of your process, locally — layer by layer, in sequence, yours alone. As Workings grows, new tools will draw richer authorship and productivity insight from work you capture today — and you decide if and when to dig in.",
      },
    ],
  },
  {
    heading: "Platform & access",
    items: [
      {
        q: "What platforms is Workings available on?",
        a: "Windows PCs (8GB RAM) and Mac (Apple Silicon).",
      },
      {
        q: "Is Workings available in my country?",
        a: "Workings is initially available to residents of the UK, Europe, Australia, and the United States.",
      },
      {
        q: "What languages does Workings support?",
        a: "English only at launch.",
      },
      {
        q: "How do I access the free beta?",
        a: 'The beta was released in May 2026 by invite only to an initial set of individual users, with more users being added over time. Join our <a href="/#early-access">waitlist</a> and we will send you an invite when you reach the front of the queue.',
      },
    ],
  },
];

export const faqItems: FaqItem[] = faqSections.flatMap((s) => s.items);
