'use client';

import { motion } from 'framer-motion';
import { useState } from 'react';

const proofCards = [
  {
    title: 'Authenticity',
    description:
      'The report was generated by Workings. It originated from our platform and has not been fabricated or spoofed by a third party.',
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
        <polyline points="9 12 12 15 16 10" />
      </svg>
    ),
  },
  {
    title: 'Integrity',
    description:
      "The data hasn't been tampered with since creation. Every field, timestamp, and metric matches the original record exactly as it was stored.",
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
        <path d="M7 11V7a5 5 0 0 1 10 0v4" />
      </svg>
    ),
  },
  {
    title: 'Process',
    description:
      'A real creative process was recorded. The report reflects genuine human work, with transparent metrics on human input and AI assistance.',
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
      </svg>
    ),
  },
];

const mockResult = {
  reportId: 'WRK-2026-04A-7F3D',
  status: 'Verified',
  created: 'April 2, 2026',
  duration: '4h 32m',
  humanPercent: 87,
  aiPercent: 13,
};

function ContributionRing({ human, ai }: { human: number; ai: number }) {
  const radius = 54;
  const circumference = 2 * Math.PI * radius;
  const humanArc = (human / 100) * circumference;
  const aiArc = (ai / 100) * circumference;

  return (
    <div className="relative w-44 h-44 sm:w-52 sm:h-52" role="img" aria-label={`Contribution ring: ${human}% human, ${ai}% AI`}>
      <svg className="w-full h-full -rotate-90" viewBox="0 0 128 128" aria-hidden="true">
        {/* Track */}
        <circle cx="64" cy="64" r={radius} fill="none" stroke="rgba(245,239,228,0.12)" strokeWidth="10" />
        {/* AI arc */}
        <motion.circle
          cx="64"
          cy="64"
          r={radius}
          fill="none"
          stroke="#5b6079"
          strokeWidth="10"
          strokeLinecap="round"
          strokeDasharray={`${aiArc} ${circumference - aiArc}`}
          strokeDashoffset={-humanArc}
          initial={{ strokeDasharray: `0 ${circumference}` }}
          animate={{ strokeDasharray: `${aiArc} ${circumference - aiArc}` }}
          transition={{ delay: 1.2, duration: 0.8, ease: 'easeOut' }}
        />
        {/* Human arc */}
        <motion.circle
          cx="64"
          cy="64"
          r={radius}
          fill="none"
          stroke="#0048ff"
          strokeWidth="10"
          strokeLinecap="round"
          strokeDasharray={`${humanArc} ${circumference - humanArc}`}
          initial={{ strokeDasharray: `0 ${circumference}` }}
          animate={{ strokeDasharray: `${humanArc} ${circumference - humanArc}` }}
          transition={{ delay: 0.8, duration: 1, ease: 'easeOut' }}
        />
      </svg>
      {/* Center text */}
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <motion.span
          className="text-3xl sm:text-4xl font-black text-cream font-display"
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 1, duration: 0.5, type: 'spring' }}
          aria-hidden="true"
        >
          {human}%
        </motion.span>
        <span className="eyebrow text-cream/60 mt-1" aria-hidden="true">Human</span>
      </div>
    </div>
  );
}

function VerifyResult() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
    >
      {/* Navy proof panel */}
      <div className="rounded-2xl bg-navy overflow-hidden border border-navy/10">
        {/* Top verified banner */}
        <motion.div
          className="border-b border-cream/10 px-6 sm:px-8 py-4 flex items-center justify-between"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2, duration: 0.4 }}
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-blue/30 bg-blue/10">
            <motion.svg
              className="w-4 h-4 text-blue"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <motion.path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                initial={{ pathLength: 0 }}
                animate={{ pathLength: 1 }}
                transition={{ delay: 0.4, duration: 0.6 }}
              />
            </motion.svg>
            <span className="text-sm font-semibold text-blue">Verified</span>
          </div>
          <span className="font-mono text-sm text-cream/50">{mockResult.reportId}</span>
        </motion.div>

        {/* Main content: two columns */}
        <div className="flex flex-col md:flex-row">
          {/* Left: contribution ring */}
          <div className="flex flex-col items-center justify-center gap-4 p-8 sm:p-10 md:border-r border-b md:border-b-0 border-cream/10">
            <ContributionRing human={mockResult.humanPercent} ai={mockResult.aiPercent} />
            {/* Ring legend */}
            <div className="flex items-center gap-4">
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-blue" aria-hidden="true" />
                <span className="text-xs text-cream/70">Human</span>
              </span>
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-mute" aria-hidden="true" />
                <span className="text-xs text-cream/70">AI</span>
              </span>
            </div>
          </div>

          {/* Right: details */}
          <div className="flex-1 p-6 sm:p-8">
            <div className="space-y-0">
              {[
                {
                  label: 'Status',
                  value: <span className="text-blue font-semibold">{mockResult.status}</span>,
                },
                { label: 'Report ID', value: <span className="font-mono text-cream/80">{mockResult.reportId}</span> },
                { label: 'Created', value: mockResult.created },
                { label: 'Duration', value: mockResult.duration },
                {
                  label: 'Contribution',
                  value: (
                    <div className="flex items-center gap-3">
                      <span className="flex items-center gap-1.5">
                        <span className="w-2 h-2 rounded-full bg-blue" aria-hidden="true" />
                        <span className="text-sm text-cream/80">Human {mockResult.humanPercent}%</span>
                      </span>
                      <span className="flex items-center gap-1.5">
                        <span className="w-2 h-2 rounded-full bg-mute" aria-hidden="true" />
                        <span className="text-sm text-cream/50">AI {mockResult.aiPercent}%</span>
                      </span>
                    </div>
                  ),
                },
              ].map((row, i) => (
                <motion.div
                  key={row.label}
                  className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-1 py-4 border-b border-cream/[0.07] last:border-b-0"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.4 + i * 0.1, duration: 0.4 }}
                >
                  <span className="eyebrow text-cream/40">{row.label}</span>
                  <span className="text-cream">{row.value}</span>
                </motion.div>
              ))}
            </div>

            {/* View full report */}
            <motion.div
              className="pt-6"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1, duration: 0.4 }}
            >
              <a
                href="#"
                className="btn-ghost-cream text-sm"
              >
                View Full Report
                <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24" aria-hidden="true">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                </svg>
              </a>
            </motion.div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

export default function VerifyPage() {
  const [showResult, setShowResult] = useState(true);

  return (
    <div className="surface-cream min-h-screen overflow-x-hidden">
      <main className="max-w-4xl mx-auto pt-32 sm:pt-40 pb-24 sm:pb-32 px-4 sm:px-6 lg:px-8">

        {/* Hero */}
        <motion.header
          className="mb-12 sm:mb-16"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <p className="eyebrow text-blue mb-4">Proof of Work</p>
          <h1 className="font-display text-5xl sm:text-6xl md:text-7xl text-navy mb-6">
            Verify a Report
          </h1>
          <p className="text-mute text-xl max-w-2xl leading-relaxed">
            Anyone can verify that a report is genuine. Enter the report ID
            below to confirm its authenticity, integrity, and the creative
            process behind it.
          </p>
        </motion.header>

        {/* Search input */}
        <motion.div
          className="mb-12 sm:mb-16"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.6 }}
        >
          <div className="flex flex-col sm:flex-row gap-3">
            <label htmlFor="report-id" className="sr-only">Report ID</label>
            <input
              id="report-id"
              type="text"
              placeholder="Enter report ID — e.g. WRK-2026-04A-7F3D"
              className="flex-1 bg-white border border-navy/10 rounded-xl px-5 py-4 text-navy placeholder-mute/50 focus:outline-none focus:border-blue focus:ring-2 focus:ring-blue/20 transition text-base font-mono"
            />
            <button
              onClick={() => setShowResult(true)}
              className="btn-blue shrink-0 rounded-xl px-8 py-4 text-base font-bold"
            >
              Verify
            </button>
          </div>
        </motion.div>

        {/* Result */}
        {showResult && (
          <div className="mb-20 sm:mb-28">
            <VerifyResult />
          </div>
        )}

        {/* What does verification prove */}
        <div>
          <div className="mb-12 sm:mb-14">
            <motion.p
              className="eyebrow text-blue mb-4"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              Three guarantees
            </motion.p>
            <motion.h2
              className="font-display text-3xl sm:text-4xl text-navy mb-4"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.05, duration: 0.6 }}
            >
              What does verification prove?
            </motion.h2>
            <motion.p
              className="text-mute text-lg max-w-2xl"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1, duration: 0.6 }}
            >
              Each Workings report is cryptographically signed and timestamped.
              Verification confirms three things.
            </motion.p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
            {proofCards.map((card, i) => (
              <motion.div
                key={card.title}
                className="card-on-cream p-8 h-full"
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.3 }}
                transition={{
                  delay: i * 0.1,
                  duration: 0.6,
                  ease: 'easeOut',
                }}
              >
                {/* Step number */}
                <span className="eyebrow text-navy/20 text-4xl font-black leading-none block mb-5">
                  0{i + 1}
                </span>

                {/* Icon */}
                <div className="w-10 h-10 rounded-xl flex items-center justify-center mb-5 bg-blue/8 border border-blue/20 text-blue">
                  {card.icon}
                </div>

                <h3 className="text-base font-bold text-navy mb-2">
                  {card.title}
                </h3>
                <p className="text-mute text-sm leading-relaxed">
                  {card.description}
                </p>

                {/* Bottom accent */}
                <motion.div
                  className="mt-6 h-px bg-blue/20"
                  initial={{ scaleX: 0, opacity: 0 }}
                  whileInView={{ scaleX: 1, opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 + 0.4, duration: 0.8, ease: 'easeOut' }}
                  style={{ transformOrigin: 'left' }}
                />
              </motion.div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
