'use client';

import { motion } from 'framer-motion';
import { useState } from 'react';
import { FloatingParticles } from '@/components/FloatingParticles';
import { GradientOrbs } from '@/components/GradientOrbs';

const proofCards = [
  {
    title: 'Authenticity',
    description:
      'The report was generated by Wolfmax. It originated from our platform and has not been fabricated or spoofed by a third party.',
    color: 'var(--brand-red)',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
        <polyline points="9 12 12 15 16 10" />
      </svg>
    ),
  },
  {
    title: 'Integrity',
    description:
      'The data hasn\'t been tampered with since creation. Every field, timestamp, and metric matches the original record exactly as it was stored.',
    color: 'var(--brand-blue)',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
        <path d="M7 11V7a5 5 0 0 1 10 0v4" />
      </svg>
    ),
  },
  {
    title: 'Process',
    description:
      'A real creative process was recorded. The report reflects genuine human work, with transparent metrics on human input and AI assistance.',
    color: 'var(--brand-green)',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
      </svg>
    ),
  },
];

const mockResult = {
  reportId: 'WMX-2026-04A-7F3D',
  status: 'Verified',
  created: 'April 2, 2026',
  duration: '4h 32m',
  humanPercent: 87,
  aiPercent: 13,
};

function ContributionRing({ human, ai }: { human: number; ai: number }) {
  const radius = 54;
  const circumference = 2 * Math.PI * radius;
  const humanArc = (human / 100) * circumference;
  const aiArc = (ai / 100) * circumference;

  return (
    <div className="relative w-40 h-40 sm:w-48 sm:h-48">
      <svg className="w-full h-full -rotate-90" viewBox="0 0 128 128">
        {/* Track */}
        <circle cx="64" cy="64" r={radius} fill="none" stroke="rgba(255,255,255,0.04)" strokeWidth="10" />
        {/* AI arc */}
        <motion.circle
          cx="64"
          cy="64"
          r={radius}
          fill="none"
          stroke="rgba(255,255,255,0.15)"
          strokeWidth="10"
          strokeLinecap="round"
          strokeDasharray={`${aiArc} ${circumference - aiArc}`}
          strokeDashoffset={-humanArc}
          initial={{ strokeDasharray: `0 ${circumference}` }}
          animate={{ strokeDasharray: `${aiArc} ${circumference - aiArc}` }}
          transition={{ delay: 1.2, duration: 0.8, ease: 'easeOut' }}
        />
        {/* Human arc */}
        <motion.circle
          cx="64"
          cy="64"
          r={radius}
          fill="none"
          stroke="var(--brand-red)"
          strokeWidth="10"
          strokeLinecap="round"
          strokeDasharray={`${humanArc} ${circumference - humanArc}`}
          initial={{ strokeDasharray: `0 ${circumference}` }}
          animate={{ strokeDasharray: `${humanArc} ${circumference - humanArc}` }}
          transition={{ delay: 0.8, duration: 1, ease: 'easeOut' }}
        />
      </svg>
      {/* Center text */}
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <motion.span
          className="text-3xl sm:text-4xl font-black text-white"
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 1, duration: 0.5, type: 'spring' }}
        >
          {human}%
        </motion.span>
        <span className="text-xs text-gray-500 uppercase tracking-wider mt-1">Human</span>
      </div>
    </div>
  );
}

function VerifyResult() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
    >
      <div className="relative">
        {/* Outer glow */}
        <div
          className="absolute -inset-1 rounded-3xl blur-2xl opacity-[0.08]"
          style={{
            background: 'linear-gradient(135deg, var(--brand-green), var(--brand-blue))',
          }}
        />

        <div className="relative overflow-hidden rounded-2xl bg-white/[0.03] border border-white/[0.06]">
          {/* Top verified banner */}
          <motion.div
            className="border-b border-white/[0.05] px-6 sm:px-8 py-4 flex items-center justify-between"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.2, duration: 0.4 }}
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-emerald-500/30 bg-emerald-500/10">
              <motion.svg
                className="w-4 h-4 text-emerald-400"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
                viewBox="0 0 24 24"
                initial={{ pathLength: 0 }}
                animate={{ pathLength: 1 }}
                transition={{ delay: 0.4, duration: 0.6 }}
              >
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </motion.svg>
              <span className="text-sm font-semibold text-emerald-400">Verified</span>
            </div>
            <span className="font-mono text-sm text-gray-500">{mockResult.reportId}</span>
          </motion.div>

          {/* Main content: two columns */}
          <div className="flex flex-col md:flex-row">
            {/* Left: contribution ring */}
            <div className="flex items-center justify-center p-8 sm:p-10 md:border-r border-b md:border-b-0 border-white/[0.05]">
              <ContributionRing human={mockResult.humanPercent} ai={mockResult.aiPercent} />
            </div>

            {/* Right: details */}
            <div className="flex-1 p-6 sm:p-8">
              <div className="space-y-0">
                {[
                  { label: 'Status', value: <span className="text-emerald-400 font-semibold">{mockResult.status}</span> },
                  { label: 'Created', value: mockResult.created },
                  { label: 'Duration', value: mockResult.duration },
                  {
                    label: 'Contribution',
                    value: (
                      <div className="flex items-center gap-3">
                        <span className="flex items-center gap-1.5">
                          <span className="w-2 h-2 rounded-full bg-brand-red" />
                          <span className="text-sm">Human {mockResult.humanPercent}%</span>
                        </span>
                        <span className="flex items-center gap-1.5">
                          <span className="w-2 h-2 rounded-full bg-white/20" />
                          <span className="text-sm text-gray-400">AI {mockResult.aiPercent}%</span>
                        </span>
                      </div>
                    ),
                  },
                ].map((row, i) => (
                  <motion.div
                    key={row.label}
                    className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-1 py-4 border-b border-white/[0.05] last:border-b-0"
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.4 + i * 0.1, duration: 0.4 }}
                  >
                    <span className="text-sm text-gray-500">{row.label}</span>
                    <span className="text-white">{row.value}</span>
                  </motion.div>
                ))}
              </div>

              {/* View full report */}
              <motion.div
                className="pt-5"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 1, duration: 0.4 }}
              >
                <a
                  href="#"
                  className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/[0.04] border border-white/[0.08] text-white text-sm font-semibold hover:bg-white/[0.08] hover:border-white/[0.15] transition-all group"
                >
                  View Full Report
                  <svg className="w-4 h-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                  </svg>
                </a>
              </motion.div>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

export default function VerifyPage() {
  const [showResult, setShowResult] = useState(true);

  return (
    <div className="relative min-h-screen bg-black overflow-x-hidden">
      {/* Background effects */}
      <div className="fixed inset-0 grid-bg pointer-events-none" />
      <FloatingParticles />
      <GradientOrbs />

      <main className="relative z-10 max-w-6xl mx-auto pt-32 sm:pt-40 pb-24 sm:pb-32 px-4 sm:px-6 lg:px-8">
        {/* Hero */}
        <motion.header
          className="mb-12 sm:mb-16"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <h1 className="text-5xl sm:text-6xl md:text-7xl font-bold text-white mb-6 tracking-tight">
            Verify a <span className="text-brand-red">Report</span>
          </h1>
          <p className="text-gray-400 text-xl max-w-2xl leading-relaxed">
            Anyone can verify that a report is genuine. Enter the report ID
            below to confirm its authenticity, integrity, and the creative
            process behind it.
          </p>
        </motion.header>

        {/* Search input */}
        <motion.div
          className="mb-12 sm:mb-16"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.6 }}
        >
          <div className="flex flex-col sm:flex-row gap-3">
            <input
              type="text"
              placeholder="Enter report ID e.g. WMX-2026-04A-7F3D"
              className="flex-1 bg-white/[0.04] border border-white/[0.08] rounded-xl px-5 py-4 text-white placeholder-gray-600 focus:outline-none focus:border-brand-red/50 focus:ring-1 focus:ring-brand-red/30 transition text-base font-mono"
            />
            <button
              onClick={() => setShowResult(true)}
              className="px-8 py-4 bg-brand-red text-white font-bold rounded-xl hover:scale-[1.02] transition-transform pulse-glow shrink-0 text-base"
            >
              Verify
            </button>
          </div>
        </motion.div>

        {/* Result */}
        {showResult && (
          <div className="mb-24 sm:mb-32">
            <VerifyResult />
          </div>
        )}

        {/* What does verification prove */}
        <div>
          <div className="mb-12 sm:mb-16">
            <motion.h2
              className="text-3xl sm:text-4xl font-bold text-white mb-4"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              What does verification prove?
            </motion.h2>
            <motion.p
              className="text-gray-400 text-lg max-w-2xl"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1, duration: 0.6 }}
            >
              Each Wolfmax report is cryptographically signed and timestamped.
              Verification confirms three things.
            </motion.p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
            {proofCards.map((card, i) => (
              <motion.div
                key={card.title}
                className="relative group"
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.3 }}
                transition={{
                  delay: i * 0.12,
                  duration: 0.7,
                  ease: 'easeOut',
                }}
              >
                <div className="relative overflow-hidden rounded-2xl bg-white/[0.03] border border-white/[0.06] p-8 h-full transition-all duration-500 group-hover:bg-white/[0.05] group-hover:border-white/[0.12]">
                  {/* Corner gradient */}
                  <div
                    className="absolute top-0 right-0 w-32 h-32 opacity-[0.04] group-hover:opacity-[0.08] transition-opacity duration-500"
                    style={{
                      background: `radial-gradient(circle at top right, ${card.color}, transparent 70%)`,
                    }}
                  />

                  {/* Step number */}
                  <span
                    className="text-5xl font-black tracking-tight leading-none opacity-15 absolute top-6 right-6"
                    style={{ color: card.color }}
                  >
                    {i + 1}
                  </span>

                  {/* Icon */}
                  <motion.div
                    className="w-11 h-11 rounded-xl flex items-center justify-center mb-5 border"
                    style={{
                      borderColor: `color-mix(in srgb, ${card.color} 30%, transparent)`,
                      background: `color-mix(in srgb, ${card.color} 8%, transparent)`,
                      color: card.color,
                    }}
                    whileHover={{ scale: 1.1 }}
                    transition={{
                      type: 'spring',
                      stiffness: 400,
                      damping: 15,
                    }}
                  >
                    {card.icon}
                  </motion.div>

                  <h3 className="text-lg font-bold text-white mb-2">
                    {card.title}
                  </h3>
                  <p className="text-gray-400 text-sm leading-relaxed">
                    {card.description}
                  </p>

                  {/* Bottom accent line */}
                  <motion.div
                    className="absolute bottom-0 left-8 right-8 h-px"
                    style={{
                      background: `linear-gradient(90deg, transparent, ${card.color}, transparent)`,
                    }}
                    initial={{ scaleX: 0, opacity: 0 }}
                    whileInView={{ scaleX: 1, opacity: 0.3 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.12 + 0.5, duration: 0.8 }}
                  />
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
