'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Eyebrow } from '@/components/Eyebrow';

const proves = [
  {
    title: 'Authenticity',
    description:
      'The report was generated by Workings. It originated from our platform and has not been fabricated or spoofed by a third party.',
    icon: 'M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z',
  },
  {
    title: 'Integrity',
    description:
      "The data hasn't been tampered with since creation. Every field, timestamp, and metric matches the original record exactly.",
    icon: 'M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z',
  },
  {
    title: 'Process',
    description:
      'A real creative process was recorded. The report reflects genuine human work, with transparent metrics on human input and AI assistance.',
    icon: 'M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z',
  },
];

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <>
      <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
        <span className="text-sm text-mute">{label}</span>
        <span className="text-navy">{children}</span>
      </div>
      <hr className="border-navy/[0.08]" />
    </>
  );
}

export default function VerifyPage() {
  const [id, setId] = useState('');

  return (
    <main className="surface-cream">
      {/* Hero */}
      <section className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pt-32 sm:pt-40 pb-12 text-center">
        <Eyebrow className="text-mute mb-4">Verify</Eyebrow>
        <h1 className="font-display text-5xl sm:text-6xl text-navy leading-[1.04] mb-6">
          Verify a <em className="italic">Workings</em> report.
        </h1>
        <p className="font-subtitle text-base sm:text-lg text-mute max-w-xl mx-auto">
          Anyone can verify a report is genuine. Enter the report ID to confirm its authenticity, integrity, and the
          creative process behind it.
        </p>
      </section>

      {/* Input */}
      <section className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 pb-12">
        <form className="flex flex-col gap-3 sm:flex-row" onSubmit={(e) => e.preventDefault()}>
          <input
            type="text"
            value={id}
            onChange={(e) => setId(e.target.value)}
            placeholder="e.g. WMX-2026-04A-7F3D"
            className="flex-1 rounded-full border border-navy/15 bg-white px-6 py-4 font-mono text-base text-navy placeholder-mute transition focus:border-blue focus:outline-none"
          />
          <button type="submit" className="btn-blue shrink-0 justify-center !px-8 !py-4">
            Verify
          </button>
        </form>
      </section>

      {/* Sample result */}
      <section className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 pb-20">
        <div className="card-on-cream p-6 md:p-8">
          <div className="mb-6 flex items-center gap-3">
            <span className="inline-flex items-center gap-2 rounded-full border border-emerald-500/40 bg-emerald-500/10 px-4 py-2 font-mono text-xs font-semibold uppercase tracking-widest text-emerald-700">
              <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2.5} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              Verified
            </span>
            <span className="font-mono text-xs text-mute">Sample report</span>
          </div>

          <div className="space-y-4">
            <Row label="Report ID">
              <span className="font-mono font-semibold">WMX-2026-04A-7F3D</span>
            </Row>
            <Row label="Status">
              <span className="font-semibold text-emerald-700">Verified</span>
            </Row>
            <Row label="Created">2 April 2026</Row>
            <Row label="Duration">4h 32m</Row>
            <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
              <span className="text-sm text-mute">Contribution</span>
              <div className="flex items-center gap-3 text-sm">
                <span className="text-navy">
                  Human: <span className="font-semibold text-blue">87%</span>
                </span>
                <span className="text-navy/30">|</span>
                <span className="text-navy">
                  AI: <span className="font-semibold text-mute">13%</span>
                </span>
              </div>
            </div>
            <div className="h-2 w-full overflow-hidden rounded-full bg-navy/[0.08]">
              <div className="h-full rounded-full bg-blue" style={{ width: '87%' }} />
            </div>
          </div>
        </div>
      </section>

      {/* What verification proves */}
      <section className="surface-navy px-4 sm:px-6 lg:px-8 py-20 sm:py-24">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <Eyebrow className="text-blue mb-3">What verification proves</Eyebrow>
            <h2 className="font-display text-3xl sm:text-5xl text-cream leading-[1.1] max-w-[20ch] mx-auto">
              Three things, cryptographically guaranteed.
            </h2>
            <p className="text-cream/70 max-w-2xl mx-auto mt-4">
              Each <em className="italic">Workings</em> report is cryptographically signed and timestamped.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 sm:gap-6">
            {proves.map((p, i) => (
              <motion.div
                key={p.title}
                className="card-on-navy p-7 sm:p-8 h-full"
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.3 }}
                transition={{ delay: i * 0.08, duration: 0.55 }}
              >
                <div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-blue/[0.18] text-blue">
                  <svg className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d={p.icon} />
                  </svg>
                </div>
                <h3 className="text-lg font-bold text-cream mb-2.5">{p.title}</h3>
                <p className="text-cream/70 text-sm leading-relaxed">{p.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
